apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
  namespace: openshift-operators-redhat
spec:
  channel: $LOKI_CHANNEL
  name: loki-operator
  source: $LOKI_SOURCE
  sourceNamespace: openshift-marketplace
