FROM registry.ci.openshift.org/ci/opm-builder:latest as opm-builder
FROM registry.ci.openshift.org/ci/ocp-qe-perfscale-ci:latest
COPY --from=opm-builder /bin/opm /usr/bin/opm
COPY scripts scripts
ENV HOME=/home/user
RUN mkdir -p /home/user && curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip" && unzip awscli-bundle.zip && awscli-bundle/install -b $HOME/bin/aws
ENV PATH="$PATH:$HOME/bin"
ADD https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 $HOME/bin/yq
RUN chmod +x $HOME/bin/yq
