apiVersion: v1
items:
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata:
    creationTimestamp: null
    labels:
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-role: infra
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-type: infra
    name: infra-${CLUSTER_REGION}a
    namespace: openshift-machine-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
        ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machineset: infra-${CLUSTER_REGION}a
    template:
      metadata:
        creationTimestamp: null
        labels:
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-role: infra
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-type: infra
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machineset: infra-${CLUSTER_REGION}a
      spec:
        metadata:
          creationTimestamp: null
          labels:
            node-role.kubernetes.io/infra: ""
        providerSpec:
          value:
            ami:
              id: ${AMI_ID}
            apiVersion: awsproviderconfig.openshift.io/v1beta1
            blockDevices:
            - ebs:
                iops: ${OPENSHIFT_INFRA_NODE_VOLUME_IOPS}
                volumeSize: ${OPENSHIFT_INFRA_NODE_VOLUME_SIZE}
                volumeType: ${OPENSHIFT_INFRA_NODE_VOLUME_TYPE}
            credentialsSecret:
              name: aws-cloud-credentials
            deviceIndex: 0
            iamInstanceProfile:
              id: ${CLUSTER_NAME}-worker-profile
            instanceType: ${OPENSHIFT_INFRA_NODE_INSTANCE_TYPE}
            kind: AWSMachineProviderConfig
            metadata:
              creationTimestamp: null
            placement:
              availabilityZone: ${CLUSTER_REGION}a
              region: ${CLUSTER_REGION}
            publicIp: false
            securityGroups:
            - filters:
              - name: tag:Name
                values:
                - ${CLUSTER_NAME}-worker-sg
            subnet:
              filters:
              - name: tag:Name
                values:
                - ${CLUSTER_NAME}-private-${CLUSTER_REGION}a
            tags:
            - name: kubernetes.io/cluster/${CLUSTER_NAME}
              value: owned
            userDataSecret:
              name: worker-user-data
        versions:
          kubelet: ""
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata:
    creationTimestamp: null
    labels:
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-role: infra
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-type: infra
    name: infra-${CLUSTER_REGION}b
    namespace: openshift-machine-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
        ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machineset: infra-${CLUSTER_REGION}b
    template:
      metadata:
        creationTimestamp: null
        labels:
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-role: infra
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-type: infra
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machineset: infra-${CLUSTER_REGION}b
      spec:
        metadata:
          creationTimestamp: null
          labels:
            node-role.kubernetes.io/infra: ""
        providerSpec:
          value:
            ami:
              id: ${AMI_ID}
            apiVersion: awsproviderconfig.openshift.io/v1beta1
            blockDevices:
            - ebs:
                iops: ${OPENSHIFT_INFRA_NODE_VOLUME_IOPS}
                volumeSize: ${OPENSHIFT_INFRA_NODE_VOLUME_SIZE}
                volumeType: ${OPENSHIFT_INFRA_NODE_VOLUME_TYPE}
            credentialsSecret:
              name: aws-cloud-credentials
            deviceIndex: 0
            iamInstanceProfile:
              id: ${CLUSTER_NAME}-worker-profile
            instanceType: ${OPENSHIFT_INFRA_NODE_INSTANCE_TYPE}
            kind: AWSMachineProviderConfig
            metadata:
              creationTimestamp: null
            placement:
              availabilityZone: ${CLUSTER_REGION}b
              region: ${CLUSTER_REGION}
            publicIp: false
            securityGroups:
            - filters:
              - name: tag:Name
                values:
                - ${CLUSTER_NAME}-worker-sg
            subnet:
              filters:
              - name: tag:Name
                values:
                - ${CLUSTER_NAME}-private-${CLUSTER_REGION}b
            tags:
            - name: kubernetes.io/cluster/${CLUSTER_NAME}
              value: owned
            userDataSecret:
              name: worker-user-data
        versions:
          kubelet: ""
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata:
    creationTimestamp: null
    labels:
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-role: infra
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-type: infra
    name: infra-${CLUSTER_REGION}c
    namespace: openshift-machine-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
        ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machineset: infra-${CLUSTER_REGION}c
    template:
      metadata:
        creationTimestamp: null
        labels:
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-role: infra
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-type: infra
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machineset: infra-${CLUSTER_REGION}c
      spec:
        metadata:
          creationTimestamp: null
          labels:
            node-role.kubernetes.io/infra: ""
        providerSpec:
          value:
            ami:
              id: ${AMI_ID}
            apiVersion: awsproviderconfig.openshift.io/v1beta1
            blockDevices:
            - ebs:
                iops: ${OPENSHIFT_INFRA_NODE_VOLUME_IOPS}
                volumeSize: ${OPENSHIFT_INFRA_NODE_VOLUME_SIZE}
                volumeType: ${OPENSHIFT_INFRA_NODE_VOLUME_TYPE}
            credentialsSecret:
              name: aws-cloud-credentials
            deviceIndex: 0
            iamInstanceProfile:
              id: ${CLUSTER_NAME}-worker-profile
            instanceType: ${OPENSHIFT_INFRA_NODE_INSTANCE_TYPE}
            kind: AWSMachineProviderConfig
            metadata:
              creationTimestamp: null
            placement:
              availabilityZone: ${CLUSTER_REGION}c
              region: ${CLUSTER_REGION}
            publicIp: false
            securityGroups:
            - filters:
              - name: tag:Name
                values:
                - ${CLUSTER_NAME}-worker-sg
            subnet:
              filters:
              - name: tag:Name
                values:
                - ${CLUSTER_NAME}-private-${CLUSTER_REGION}c
            tags:
            - name: kubernetes.io/cluster/${CLUSTER_NAME}
              value: owned
            userDataSecret:
              name: worker-user-data
        versions:
          kubelet: ""
kind: List
metadata: {}
