apiVersion: v1
kind: ConfigMap
data:
  config.yaml: |
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    prometheusK8s:
      retention: ${OPENSHIFT_PROMETHEUS_RETENTION_PERIOD}
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      volumeClaimTemplate:
        spec:
          storageClassName: ${OPENSHIFT_PROMETHEUS_STORAGE_CLASS}
          resources:
            requests:
              storage: ${OPENSHIFT_PROMETHEUS_STORAGE_SIZE}
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      volumeClaimTemplate:
        spec:
          storageClassName: ${OPENSHIFT_ALERTMANAGER_STORAGE_CLASS}
          resources:
            requests:
              storage: ${OPENSHIFT_ALERTMANAGER_STORAGE_SIZE}
    metricsServer:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring