apiVersion: v1
kind: ConfigMap
data:
  config.yaml: |
    prometheusOperator:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    prometheusK8s:
      retention: ${OPENSHIFT_PROMETHEUS_RETENTION_PERIOD}
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    alertmanagerMain:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    kubeStateMetrics:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    grafana:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
    k8sPrometheusAdapter:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring