apiVersion: v1
items:
- apiVersion: machine.openshift.io/v1beta1
  kind: MachineSet
  metadata:
    labels:
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-role: workload
      ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-type: workload
    name: ${CLUSTER_NAME}-workload
    namespace: openshift-machine-api
    annotations: 
      machine.openshift.io/memoryMb: "16384"
      machine.openshift.io/vCPU: "4"
  spec:
    replicas: 1
    selector:
      matchLabels:
        ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
        ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machineset: ${CLUSTER_NAME}-workload
    template:
      metadata:
        labels:
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-cluster: ${CLUSTER_NAME}
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-role: workload
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machine-type: workload
          ${MACHINESET_METADATA_LABEL_PREFIX}/cluster-api-machineset: ${CLUSTER_NAME}-workload
      spec:
        metadata:
          labels:
            node-role.kubernetes.io/workload: ""
        providerSpec:
          value:
            apiVersion: machine.openshift.io/v1
            cluster:
              type: uuid
              uuid: ${CLUSTER_UUID}
            credentialsSecret:
              name: nutanix-credentials
            image:
              name: ${CLUSTER_NAME}-rhcos
              type: name
            kind: NutanixMachineProviderConfig
            memorySize: ${OPENSHIFT_WORKLOAD_NODE_INSTANCE_MEMORYSIZE}
            subnets:
            - type: uuid
              uuid: ${SUBNET_UUID}
            systemDiskSize: 120Gi
            userDataSecret:
              name: worker-user-data
            vcpuSockets: ${OPENSHIFT_WORKLOAD_NODE_INSTANCE_VCPU}
            vcpusPerSocket: 1
        # taints:
        # - key: node-role.kubernetes.io/workload
        #   effect: NoSchedule
kind: List
metadata: {}
