apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: netobserv-operator
  namespace: openshift-operators
spec:
  channel: v1.0.x
  name: netobserv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace 
