apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: netobserv-main-testing
  namespace: openshift-marketplace
spec:
  displayName: NetObservMainTesting
  image: 'quay.io/netobserv/network-observability-operator-catalog:v0.0.0-main'
  sourceType: grpc
