apiVersion: v1
kind: Namespace
metadata:
  name: openshift-netobserv-operator
  labels:
    openshift.io/cluster-monitoring: "true"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-netobserv-operator-prometheus
  namespace: openshift-netobserv-operator
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-netobserv-operator-prometheus
  namespace: openshift-netobserv-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-netobserv-operator-prometheus
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring

---

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: netobserv-operator
  namespace: openshift-netobserv-operator
spec:
  upgradeStrategy: Default
