apiVersion: flows.netobserv.io/v1alpha1
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  deploymentModel: DIRECT
  agent:
    type: EBPF
    ipfix:
      cacheActiveTimeout: 20s
      cacheMaxFlows: 400
      sampling: 400
      clusterNetworkOperator:
        namespace: openshift-network-operator
      ovnKubernetes:
        namespace: ovn-kubernetes
        daemonSetName: ovnkube-node
        containerName: ovnkube-node
    ebpf:
      imagePullPolicy: Always
      sampling: 1
      cacheActiveTimeout: 5s
      cacheMaxFlows: 100000
      interfaces: [ ]
      excludeInterfaces: [ "lo" ]
      logLevel: info
      privileged: false
  processor:
    port: 2055
    imagePullPolicy: Always
    logLevel: info
    enableKubeProbes: true
    healthPort: 8080
    profilePort: 6060
    metrics:
      server:
        port: 9102
      ignoreTags:
        - egress
    dropUnusedFields: true
    kafkaConsumerReplicas: 3
    kafkaConsumerAutoscaler: null
  kafka:
    address: "kafka-cluster-kafka-bootstrap.netobserv"
    topic: network-flows
    tls:
      enable: false
      caCert:
        type: secret
        name: kafka-cluster-cluster-ca-cert
        certFile: ca.crt
      userCert:
        type: secret
        name: flp-kafka
        certFile: user.crt
        certKey: user.key
  loki:
    url: https://lokistack-distributor-http.openshift-operators-redhat.svc:3100/
    querierUrl: https://lokistack-querier-http.openshift-operators-redhat.svc:3100/
    batchWait: 1s
    batchSize: 102400
    minBackoff: 1s
    maxBackoff: 300s
    maxRetries: 10
    staticLabels:
      app: netobserv-flowcollector
    tls:
      enable: true
      caCert:
        type: configmap
        name: openshift-service-ca.crt
        certFile: service-ca.crt
  consolePlugin:
    register: true
    imagePullPolicy: Always
    port: 9001
    logLevel: info
    autoscaler: null
    portNaming:
      enable: true
      portNames:
        "3100": loki
