apiVersion: flows.netobserv.io/v1alpha1
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: netobserv
  deploymentModel: DIRECT
  agent:
    type: EBPF
    ipfix:
      cacheActiveTimeout: 20s
      cacheMaxFlows: 400
      sampling: 400
      clusterNetworkOperator:
        namespace: openshift-network-operator
      ovnKubernetes:
        namespace: ovn-kubernetes
        daemonSetName: ovnkube-node
        containerName: ovnkube-node
    ebpf:
      image: 'quay.io/netobserv/netobserv-ebpf-agent:main'
      imagePullPolicy: IfNotPresent
      sampling: 50
      cacheActiveTimeout: 5s
      cacheMaxFlows: 1000
      interfaces: [ ]
      excludeInterfaces: [ "lo" ]
      logLevel: info
      privileged: false
      resources:
        requests:
          memory: 50Mi
          cpu: 100m
        limits:
          memory: 100Mi
  processor:
    port: 2055
    image: 'quay.io/netobserv/flowlogs-pipeline:main'
    imagePullPolicy: IfNotPresent
    logLevel: info
    enableKubeProbes: true
    healthPort: 8080
    profilePort: 6060
    metricsServer:
      port: 9102
    ignoreMetrics: []
    dropUnusedFields: true
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 300Mi
    kafkaConsumerReplicas: 3
    kafkaConsumerAutoscaler: null
  kafka:
    address: "kafka-cluster-kafka-bootstrap.netobserv"
    topic: network-flows
    tls:
      enable: false
      caCert:
        type: secret
        name: kafka-cluster-cluster-ca-cert
        certFile: ca.crt
      userCert:
        type: secret
        name: flp-kafka
        certFile: user.crt
        certKey: user.key
  loki:
    url: 'http://loki.netobserv.svc:3100/'
    batchWait: 1s
    batchSize: 102400
    minBackoff: 1s
    maxBackoff: 300s
    maxRetries: 10
    staticLabels:
      app: netobserv-flowcollector
    tls:
      enable: false
      caCert:
        type: configmap
        name: openshift-service-ca.crt
        certFile: service-ca.crt
  consolePlugin:
    register: true
    image: 'quay.io/netobserv/network-observability-console-plugin:main'
    imagePullPolicy: IfNotPresent
    port: 9001
    logLevel: info
    autoscaler: null
    portNaming:
      enable: true
      portNames:
        "3100": loki
