apiVersion: flows.netobserv.io/v1alpha1
kind: FlowCollector
metadata:
  name: cluster
spec:
  namespace: "network-observability"
  agent: ipfix
  ipfix:
    cacheActiveTimeout: 60s
    cacheMaxFlows: 400
    sampling: 100
  ebpf:
    image: 'quay.io/netobserv/netobserv-ebpf-agent:main'
    imagePullPolicy: Always
    sampling: 0
    cacheActiveTimeout: 5s
    cacheMaxFlows: 1000
    interfaces: []
    excludeInterfaces: ["lo"]
    logLevel: info
  flowlogsPipeline:
    kind: DaemonSet
#    kind: Deployment
#    replicas: 1
    port: 2055
    image: 'quay.io/netobserv/flowlogs-pipeline:main'
    imagePullPolicy: Always
    logLevel: info
    enableKubeProbes: true
    healthPort: 8080
  loki:
    url: 'http://loki:3100/'
    batchWait: 1s
    batchSize: 102400
    minBackoff: 1s
    maxBackoff: 300s
    maxRetries: 10
    timestampLabel: TimeFlowEnd
    staticLabels:
      app: netobserv-flowcollector
  consolePlugin:
    image: 'quay.io/netobserv/network-observability-console-plugin:main'
    imagePullPolicy: Always
    port: 9001
    logLevel: info
    portNaming:
      enable: true
      portNames:
        "3100": loki
  clusterNetworkOperator:
    namespace: "openshift-network-operator"
