apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: brew-registry
spec:
  repositoryDigestMirrors:
  - mirrors:
    - brew.registry.redhat.io
    source: registry.redhat.io
  - mirrors:
    - brew.registry.redhat.io
    source: registry.stage.redhat.io
  - mirrors:
    - brew.registry.redhat.io
    source: registry-proxy.engineering.redhat.com
  - mirrors:
    - brew.registry.redhat.io/rh-osbs/openshift-logging-cluster-logging-rhel8-operator
    source: registry.redhat.io/openshift-logging/cluster-logging-rhel8-operator
  - mirrors:
    - brew.registry.redhat.io/rh-osbs/openshift-logging-fluentd-rhel8
    source: registry.redhat.io/openshift-logging/fluentd-rhel8
  - mirrors:
    - brew.registry.redhat.io/rh-osbs/openshift-logging-logging-curator5-rhel8
    source: registry.redhat.io/openshift-logging/logging-curator5-rhel8
  - mirrors:
    - brew.registry.redhat.io/rh-osbs/openshift-logging-elasticsearch-rhel8-operator
    source: registry.redhat.io/openshift-logging/elasticsearch-rhel8-operator
  - mirrors:
    - brew.registry.redhat.io/rh-osbs/openshift-logging-elasticsearch-proxy-rhel8
    source: registry.redhat.io/openshift-logging/elasticsearch-proxy-rhel8
  - mirrors:
    - brew.registry.redhat.io/rh-osbs/openshift-logging-elasticsearch6-rhel8
    source: registry.redhat.io/openshift-logging/elasticsearch6-rhel8
  - mirrors:
    - brew.registry.redhat.io/rh-osbs/openshift-logging-kibana6-rhel8
    source: registry.redhat.io/openshift-logging/kibana6-rhel8
