apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-store
  namespace: netobserv
spec:
  resources:
    requests:
      storage: 200G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

