apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: netobserv-operator
  namespace: network-observability
spec:
  channel: alpha
  name: netobserv-operator
  source: community-operators
  sourceNamespace: openshift-marketplace 
