apiVersion: v1
kind: Service
metadata:
  labels:
    app: flowlogs-pipeline
  name: flp
  namespace: netobserv
spec:
  ports:
  - port: 9102
    protocol: TCP
    targetPort: 9102
    name: metrics
  selector:
    app: flowlogs-pipeline
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flowlogs-pipeline
  namespace: netobserv
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - netobserv
  selector:
    matchLabels:
      app: flowlogs-pipeline

